services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/node/.n8n:rw
      - ../dist/:/home/node/.n8n/custom/node_modules/n8n-nodes-planaday:ro
